apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-date-01
  namespace: quay-enterprise
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
