apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: default
spec:
  egress: 
  - type: Allow
    to:
      cidrSelector: 172.30.0.0/16
  - type: Allow
    to:
      cidrSelector: 10.128.0.0/14
  - type: Allow
    to:
      cidrSelector: 3.133.250.207/32
  - type: Allow
    to:
      cidrSelector: 3.13.168.216/32
  - type: Allow
    to:
      dnsName: example-registry-quay-quay-enterprise.apps.cluster-ptscz.ptscz.sandbox878.opentlc.com
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0

